spring:
  application:
    name: my-springboot
  datasource:
    url:                 ${DB_URL:jdbc:h2:~/tmp/db/h2/my-springboot.h2;AUTO_SERVER=TRUE;MODE=MYSQL;}
    username:            ${DB_USERNAME:sa}
    password:            ${DB_PASSWORD:sa}
    driver-class-name:   ${DB_DRIVER:org.h2.Driver}
  jpa:
    database-platform:                     ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    show-sql:                              true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show-sql:                  true
      hibernate.hbm2ddl.auto:              update
    open-in-view: true
  aop:
    proxy-target-class: true